language: java
install: true

jdk:
  - oraclejdk8

script:
  - rm gradle.properties
  - mv gradle-travisci.properties gradle.properties
  - chmod +x gradlew
  - ./gradlew build

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
